jobs:
  ANDROID_BASE_CHECKS:
    name: Base Checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Perform base checks
      run: ./gradlew demo:assembleDebug lib:publishToDirectory
  ANDROID_EMULATOR_TESTS:
    name: Emulator Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Execute emulator tests
      timeout-minutes: 30
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.EMULATOR_API }}
        arch: ${{ matrix.EMULATOR_ARCH }}
        disable-animations: true
        emulator-options: -no-snapshot -no-window -no-boot-anim -camera-back none
          -camera-front none -gpu swiftshader_indirect
        profile: Nexus 5X
        script: ./.github/workflows/emulator_script.sh
    - continue-on-error: true
      name: Upload emulator tests artifact
      uses: actions/upload-artifact@v1
      with:
        name: emulator_tests_${{ matrix.EMULATOR_API }}
        path: ./lib/build/outputs/code_coverage/debugAndroidTest/connected
    strategy:
      fail-fast: false
      matrix:
        EMULATOR_API:
        - 22
        - 25
        - 28
        include:
        - EMULATOR_API: 28
          EMULATOR_ARCH: x86_64
        - EMULATOR_API: 25
          EMULATOR_ARCH: x86
        - EMULATOR_API: 22
          EMULATOR_ARCH: x86
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
